# Generated by Django 3.0.5 on 2020-04-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='Datesold',
            field=models.CharField(max_length=100),
        ),
    ]
